### ISSUE TITLE
IRI benchmark tests 

### ISSUE THREAD

**Issue by sadjy** [iotaledger/ci-pipelines#35]
We currently have 2 benchmark tests for IRI (triggered by `mvn -Dtest=BenchmarkRunner clean test`).
- Check if the running time of the test and see if it's not too long. 
- Filter output log to retain information such as displayed here: https://github.com/iotaledger/iri/issues/924#issuecomment-417260225

**Comment by GalRogozinski** [comment]
add logs

**Comment by sadjy** [comment]
Some extra requirements:
- Make the test being able to be run manually on any IRI PR
- Make it run faster (cf. https://github.com/iotaledger/iri/pull/1663)
- Comment on the issue

**Comment by GalRogozinski** [comment]
We need to make the tests run nightly on `dev`
We need to make them work on any PR manually
We need to have them run nightly

**Comment by GalRogozinski** [comment]
We need to see stable results, and then add alerts if there's a regression of more than 5% in any of the metrics

**Comment by taraszka** [comment]
As we agreed, I am closing this ticket. There is a separate ticket for presenting the data in Grafana.
